[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"
NIXPACKS_PYTHON_VERSION = "3.13"

[phases.setup]
nixPkgs = ["python313", "uv"]

[phases.install]
cmds = ["uv sync --no-dev --frozen"]

[start]
cmd = "python app.py"